### Numpy operations

In [1]:
# Imports
import numpy as np
from machine_learning.utility import *
import random

#### Slicing

In [2]:
# 1d
arr = np.array([i for i in range(10)])
show(
    Basic_slicing = arr[:5],
    with_step = arr[0:9:2],
    Negative_indexing_slicing = arr[-3:],
     )


Basic_slicing: 
 [0 1 2 3 4]

with_step: 
 [0 2 4 6 8]

Negative_indexing_slicing: 
 [7 8 9]


In [3]:
# 2d
arr_2d = np.array([i for i in range(10)])
arr_2d = arr_2d.reshape(5,2)

show(
    orignal = arr_2d,
    _2d_indexing = arr_2d[4,1],
    _2d_slicing_col = arr_2d[:,1],
    _2d_slicing_row = arr_2d[2,:],
)


orignal: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

_2d_indexing: 
 9

_2d_slicing_col: 
 [1 3 5 7 9]

_2d_slicing_row: 
 [4 5]


#### Sorting

In [4]:
# 1d
unsorted_arr = np.array([int(random.random()*10)*i for i in range(10)])

show(
    original_arr = unsorted_arr,
    sorted_arr = np.sort(unsorted_arr)
)


original_arr: 
 [ 0  1 12  9 28  0 30 14  0 63]

sorted_arr: 
 [ 0  0  0  1  9 12 14 28 30 63]


In [5]:
# 2d
unsorted_2d = np.array([[random.randint(2,10) for _ in range(3)] for _ in range(2)])

show(
    original_2d_array = unsorted_2d,
    row_sorted_2d_array = np.sort(unsorted_2d, axis=1),
    col_sorted_2d_array = np.sort(unsorted_2d, axis=1)
)


original_2d_array: 
 [[4 8 9]
 [5 8 4]]

row_sorted_2d_array: 
 [[4 8 9]
 [4 5 8]]

col_sorted_2d_array: 
 [[4 8 9]
 [4 5 8]]


#### Filtering

In [6]:
# basic + masking
numbers = np.random.randint(7,16, size=(2,4))
odd_mask = numbers % 2 != 0
show(
    numbers = numbers,
    even_number = numbers[numbers % 2 == 0],
    masking_prime_numbers = numbers[odd_mask] 
)


numbers: 
 [[ 7 12 13 14]
 [15  9 13  8]]

even_number: 
 [12 14  8]

masking_prime_numbers: 
 [ 7 13 15  9 13]


In [7]:
# where
numbers = np.random.randint(7,28, size=(3,7))
show(
    original = np.sort(numbers),
    less_than_10 = numbers[np.where(numbers < 10)],
    condition_array = np.sort(np.where(numbers < 18, numbers*0, numbers*0 + 1))
)

# how where works: 
# if(condition1):
#    condition2
# else:
#    condition3


original: 
 [[12 13 13 15 18 18 20]
 [ 7  9 10 20 23 25 26]
 [ 8  9 13 14 18 20 22]]

less_than_10: 
 [7 9 8 9]

condition_array: 
 [[0 0 0 0 1 1 1]
 [0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1]]


#### Addition and deletion

In [8]:
# Concatenation
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,7],
                 [9,0]])

show(
    plus_result = arr1+arr2,
    row_concat_result = np.concatenate((arr1,arr2), axis=0),
    col_concat_result = np.concatenate((arr1,arr2), axis=1),
    vstack_result = np.vstack((arr1,arr2)),
    hstack_result = np.hstack((arr1,arr2)),
    compatibility_result = arr1 == arr2,
    del_row1_arr1 = np.delete(arr1,0,axis=0),
)


plus_result: 
 [[ 6  9]
 [12  4]]

row_concat_result: 
 [[1 2]
 [3 4]
 [5 7]
 [9 0]]

col_concat_result: 
 [[1 2 5 7]
 [3 4 9 0]]

vstack_result: 
 [[1 2]
 [3 4]
 [5 7]
 [9 0]]

hstack_result: 
 [[1 2 5 7]
 [3 4 9 0]]

compatibility_result: 
 [[False False]
 [False False]]

del_row1_arr1: 
 [[3 4]]
