Numpy stands for numerical python..

In [1]:
# It is used for efficiend array manipulations (better than lists)
# Provides efficient storage and faster processing for numerical and scientific computations.

# It offers function for linear algebra and random number generation making it important for data science and machine learning.

In [2]:
import os
print(os.getcwd())


d:\machine_learning\numpy\Basic


### Import

In [3]:
import numpy as np
import time as time
import random as random
from machine_learning.utility import *

### Types of array

In [4]:
# 1] One dimensional array
list1 = [x for x in range(1,10)]

np_array = np.array(list1)

print("Python list: ", list1, type(list))
print("Numpy list/array: ", np_array, type(np_array))

Python list:  [1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'type'>
Numpy list/array:  [1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [5]:
# 2] Two dimensional array
list2 = [[x, y] for x,y in zip(range(1,5), range(5,1,-1))]

np_array = np.array(list2)
print(list2)
print(np_array)

[[1, 5], [2, 4], [3, 3], [4, 2]]
[[1 5]
 [2 4]
 [3 3]
 [4 2]]


### Python lists vs numpy array

In [6]:
# Python list
@time_taken
def list_build():
    return [i**2 for i in range(100000)]


# numpy array
@time_taken
def np_build():
    return np.arange(100000)**2


list_build()
np_build()

Time taken by  list_build :  0.02231764793395996
Time taken by  np_build :  0.0007154941558837891


array([         0,          1,          4, ..., 9999400009, 9999600004,
       9999800001], shape=(100000,))

### Creating numpy arrays

In [7]:
# Zeros
zeros = np.zeros([2,3])

ones = np.ones([2,3])

full = np.full([2,3], 7)

sequence = np.arange(1, 10, 2)

random = np.random.random(10)

show(
    zeros=zeros,
    ones=ones,
    full=full,
    sequence=sequence,
    random=random
)


zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]]

ones: 
 [[1. 1. 1.]
 [1. 1. 1.]]

full: 
 [[7 7 7]
 [7 7 7]]

sequence: 
 [1 3 5 7 9]

random: 
 [0.62836317 0.46049593 0.07228419 0.7005717  0.11710159 0.94929572
 0.64493295 0.10620909 0.91461779 0.47842933]


### Vector, Matrix and Tensor

In [8]:
# Vector
vector = np.array([1,2,3])

# Matrix
matrix = np.array([[1,2,3],[4,5,6]])

# Tensor
tensor = np.array([[[1,2],[2,2]], [[3,4],[3,3]]])

show(
    vector=vector,
    matrix=matrix,
    tensor=tensor,
    np_array=np_array
)




vector: 
 [1 2 3]

matrix: 
 [[1 2 3]
 [4 5 6]]

tensor: 
 [[[1 2]
  [2 2]]

 [[3 4]
  [3 3]]]

np_array: 
 [[1 5]
 [2 4]
 [3 3]
 [4 2]]


### Numpy array properties

In [9]:
np_array = np.array([[1,2],[2,3],[5,6]])

show(shape=     np_array.shape,
     dimension= np_array.ndim,
     size=      np_array.size,
     dataType=  np_array.dtype)


shape: 
 (3, 2)

dimension: 
 2

size: 
 6

dataType: 
 int64


### Numpy array reshaping

In [10]:
np_array = np.arange(10)
reshaped = np_array.reshape(2,5)

show(orignal = np_array,
     reshaped= reshaped,
     ravel = reshaped.ravel(),
     flattened = reshaped.flatten(),
     transpose = reshaped.transpose()
     )


orignal: 
 [0 1 2 3 4 5 6 7 8 9]

reshaped: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

ravel: 
 [0 1 2 3 4 5 6 7 8 9]

flattened: 
 [0 1 2 3 4 5 6 7 8 9]

transpose: 
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
