### Random numbers generation

In [1]:
# imports and stuff
import numpy as np
from machine_learning.utility import show

random integers and floats

In [9]:
show(
    random_int_from_0_to_100 = np.random.randint(100),
    random_float = np.random.rand(),
)


random_int_from_0_to_100: 
 74

random_float: 
 0.04196675868218225


Random array of int and float

In [19]:
show(
    random_int_vector = np.random.randint(100, size=(3)),
    random_int_matrix = np.random.randint(100, size=(3,3)),
    
    random_float_vector = np.random.rand(5),
    random_float_matrix = np.random.rand(3,3)
)


random_int_vector: 
 [21 63 69]

random_int_matrix: 
 [[45 60 93]
 [85  4 80]
 [52 86 28]]

random_float_vector: 
 [0.11527945 0.12341251 0.00884315 0.73301152 0.11960389]

random_float_matrix: 
 [[0.17701986 0.53020717 0.27476048]
 [0.48996666 0.21442851 0.94574073]
 [0.43107761 0.41359059 0.95900707]]


Random number from Array

In [31]:
show(
    random_choice = np.random.choice([34,7,4,5,34]),
    randomly_choosen_numbered_array = np.random.choice([69,6,7,420], size=(3,3)),
)


random_choice: 
 34

randomly_choosen_numbered_array: 
 [[  6 420   6]
 [420   6 420]
 [ 69 420 420]]
