### Numpy operations

In [17]:
# Imports
import numpy as np
from utility import show, time_taken
import random

#### Slicing

In [18]:
# 1d
arr = np.array([i for i in range(10)])
show(
    Basic_slicing = arr[:5],
    with_step = arr[0:9:2],
    Negative_indexing_slicing = arr[-3:],
    
     )


Basic_slicing: 
 [0 1 2 3 4]

with_step: 
 [0 2 4 6 8]

Negative_indexing_slicing: 
 [7 8 9]


In [19]:
# 2d
arr_2d = np.array([i for i in range(10)])
arr_2d = arr_2d.reshape(5,2)

show(
    orignal = arr_2d,
    _2d_indexing = arr_2d[4,1],
    _2d_slicing_col = arr_2d[:,1],
    _2d_slicing_row = arr_2d[2,:],
)


orignal: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

_2d_indexing: 
 9

_2d_slicing_col: 
 [1 3 5 7 9]

_2d_slicing_row: 
 [4 5]


#### Sorting

In [20]:
# 1d
unsorted_arr = np.array([int(random.random()*10)*i for i in range(10)])

show(
    original_arr = unsorted_arr,
    sorted_arr = np.sort(unsorted_arr)
)


original_arr: 
 [ 0  7  8 24 12 25 42  0  8 63]

sorted_arr: 
 [ 0  0  7  8  8 12 24 25 42 63]


In [36]:
# 2d
unsorted_2d = np.array([[random.randint(2,10) for _ in range(3)] for _ in range(2)])

show(
    original_2d_array = unsorted_2d,
    row_sorted_2d_array = np.sort(unsorted_2d, axis=1),
    col_sorted_2d_array = np.sort(unsorted_2d, axis=1)
)


original_2d_array: 
 [[ 2  6  5]
 [ 4  2 10]]

row_sorted_2d_array: 
 [[ 2  5  6]
 [ 2  4 10]]

col_sorted_2d_array: 
 [[ 2  5  6]
 [ 2  4 10]]


#### Filtering

In [48]:
# basic + masking
numbers = np.random.randint(7,16, size=(2,4))
odd_mask = numbers % 2 != 0
show(
    numbers = numbers,
    even_number = numbers[numbers % 2 == 0],
    masking_prime_numbers = numbers[odd_mask] 
)


numbers: 
 [[ 8 13 10 11]
 [13 13 12 10]]

even_number: 
 [ 8 10 12 10]

masking_prime_numbers: 
 [13 11 13 13]


In [86]:
# where
numbers = np.random.randint(7,28, size=(3,7))
show(
    original = np.sort(numbers),
    less_than_10 = numbers[np.where(numbers < 10)],
    condition_array = np.sort(np.where(numbers < 18, numbers*0, numbers*0 + 1))
)

# how where works: 
# if(condition1):
#    condition2
# else:
#    condition3


original: 
 [[11 12 14 16 17 24 27]
 [14 18 21 21 24 26 26]
 [ 8 13 14 15 22 27 27]]

less_than_10: 
 [8]

condition_array: 
 [[0 0 0 0 0 1 1]
 [0 1 1 1 1 1 1]
 [0 0 0 0 1 1 1]]


#### Addition and deletion

In [ ]:
# Concatenation
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,7],
                 [9,0]])

show(
    plus_result = arr1+arr2,
    row_concat_result = np.concatenate((arr1,arr2), axis=0),
    col_concat_result = np.concatenate((arr1,arr2), axis=1),
    vstack_result = np.vstack((arr1,arr2)),
    hstack_result = np.hstack((arr1,arr2)),
    compatibility_result = arr1 == arr2,
    del_row1_arr1 = np.delete(arr1,0,axis=0),
)


plus_result: 
 [[ 6  9]
 [12  4]]

row_concat_result: 
 [[1 2]
 [3 4]
 [5 7]
 [9 0]]

col_concat_result: 
 [[1 2 5 7]
 [3 4 9 0]]

vstack_result: 
 [[1 2]
 [3 4]
 [5 7]
 [9 0]]

hstack_result: 
 [[1 2 5 7]
 [3 4 9 0]]

compatibility_result: 
 [[False False]
 [False False]]

del_row1_arr1: 
 [[3 4]]
